# Generated by Django 4.2.3 on 2023-07-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='Name')),
                ('password', models.CharField(max_length=16, verbose_name='Password')),
            ],
            options={
                'verbose_name_plural': 'Student Data Management',
                'db_table': 'Student',
            },
        ),
    ]
